name: Sponsors

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  update-sponsors:
    name: Update sponsor images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm i
      - name: Update sponsors
        run: npm run sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: ${{ secrets.SPONSORKIT_GITHUB_LOGIN }}
          SPONSORKIT_GITHUB_TYPE: ${{ secrets.SPONSORKIT_GITHUB_TYPE }}
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_KEY }}
          SPONSORKIT_OPENCOLLECTIVE_SLUG: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_SLUG }}
          SPONSORKIT_POLAR_TOKEN: ${{ secrets.SPONSORKIT_POLAR_TOKEN }}
      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: 'chore(images): update sponsor images'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}